import turtle
tarta = turtle.Turtle()
tarta.speed(20)
for i in range(100):
    tarta.fd(5)
    tarta.bk(10)
    tarta.right(36)
    tarta.fd(10)
    tarta.left(144)
    tarta.fd(10)
    tarta.left(144)
    tarta.fd(10)
    tarta.left(144)
    tarta.fd(10)
    tarta.pu()
    #tarta.right(46)
    tarta.fd(10)
    tarta.pd()
    #tarta.left(10)
