import turtle
from musica_piano import *
tela = turtle.Screen()
beatle = turtle.Turtle()
beatle.speed(5)
def P1():
    si3.toca(0.25)
    do.toca(0.25)
    re.tocafade(2)
    fachar.tocafade(2)
    la.tocafade(2)
    re.toca(1)
    sleep(0.25)
    si3.toca(0.25)
    la3.toca(0.25)
    si3.toca(0.25)
def P2():
    sol3.tocafade(2)
    si.tocafade(2)
    re.tocafade(2)
    sol3.toca(1.5)
    si3.toca(0.25)
    si3.toca(0.25)
    la3.tocafade(2)
    dochar.tocafade(2)
    mi.tocafade(2)
    la3.toca(0.25)
    sol3.toca(0.25)
    mi3.toca(0.75)
    mi3.toca(0.25)
    si3.toca(0.25)
    si3.toca(0.25)
    P3()
def P3():
    re.tocafade(2)
    fachar.tocafade(2)
    la.tocafade(2)
    la3.toca(1.5)
def P4():
    for i in range(2):
        sol3.tocafade(2)
        si .tocafade(2)
        re.tocafade(2)
        re.toca(0.5)
        re.toca(0.5)
        re.toca(0.5)
        re.toca(0.25)
        mi.toca(0.25)
        for i in range(2):
            re.tocafade(2)
            fachar.tocafade(2)
            la.tocafade(2)
            la3.toca(0.25)
            la3.toca(0.25)
            la3.toca(0.25)
            la3.toca(0.25)
            la3.toca(1)
        sol3.tocafade(2)
        si.tocafade(2)
        re.tocafade(2)
        sol3.toca(0.25)
        sol3.toca(0.25)
        sol3.toca(0.25)
        sol3.toca(0.25)
        sol3.toca(1)
def Musica():
    for i in range(2):
        for i in range(2):
            P1()
            P2()
        P4()
    sol3.tocafade(2)
    si.tocafade(2)
    re.tocafade(2)
    sol.toca(2)
    sol5.toca(2)
beatle.color("cyan")
beatle.goto(-500,-500)
beatle.begin_fill()
beatle.fillcolor("cyan")
for i in range(4):
    beatle.fd(1000)
    beatle.lt(90)
beatle.end_fill()
beatle.goto(0,0)
beatle.pu()
beatle.color("yellow")
beatle.bk(50)
beatle.lt(90)
beatle.bk(50)
beatle.rt(90)
beatle.pd()
beatle.begin_fill()
beatle.fillcolor("yellow")
beatle.circle(50)
beatle.end_fill()
beatle.fd(100)
beatle.begin_fill()
beatle.fillcolor("yellow")
beatle.circle(50)
beatle.end_fill()
beatle.begin_fill()
for i in range(3):
    beatle.lt(90)
    beatle.fd(100)
beatle.fillcolor("yellow")
beatle.end_fill()
beatle.color("white")
beatle.pu()
beatle.bk(25)
beatle.lt(90)
beatle.pd()
for i in range(3):
    beatle.begin_fill()
    beatle.fillcolor("white")
    beatle.circle(20)
    beatle.end_fill()
    beatle.pu()
    beatle.fd(50)
    beatle.pd()
beatle.color("yellow")
beatle.lt(90)
beatle.pu()
beatle.fd(25)



beatle.goto(-50,0)
beatle.fd(50)
beatle.pd()
beatle.begin_fill()
beatle.fillcolor("yellow")
for i in range(2):
    beatle.fd(20)
    beatle.rt(90)
    beatle.fd(100)
    beatle.rt(90)
beatle.end_fill()
beatle.pu()
beatle.goto(-20,70)
beatle.pd()
beatle.begin_fill()
beatle.fillcolor("yellow")
beatle.fd(35)
beatle.rt(90)
beatle.fd(25)
beatle.rt(90)
beatle.fd(10)
beatle.rt(90)
beatle.fd(5)
beatle.lt(90)
beatle.fd(27)
beatle.end_fill()
beatle.end_fill()
beatle.hideturtle()
Musica()
tela.mainloop()
#def acorde():
    #do.tocafade(4)
    #mi.tocafade(4)
    #sol.tocafade(4)
